import type { Plugin } from "@opencode-ai/plugin"

/**
 * Gemini Thought Signature Fix Plugin
 *
 * Fixes the unrecoverable "missing thought_signature" error that occurs with
 * Gemini 3.x thinking models during multi-turn tool-calling conversations.
 *
 * When Gemini's thinking mode produces tool calls, it returns `thoughtSignature`
 * tokens that must be echoed back in subsequent requests. OpenCode can lose these
 * signatures due to:
 *   - Model switching (the `differentModel` check strips providerMetadata)
 *   - Metadata not being stored/restored properly through the DB round-trip
 *   - OpenAI-compatible providers not supporting thoughtSignature at all
 *
 * This plugin injects Google's official sentinel value
 * `"skip_thought_signature_validator"` into any reasoning or tool-call parts
 * that are missing a valid `thoughtSignature`. This tells the Gemini API to
 * skip signature validation rather than returning a hard 400 error.
 *
 * Trade-off: The model still thinks and produces reasoning output, but cannot
 * fully restore its chain-of-thought context across tool calls. This causes
 * minor degradation in complex multi-step reasoning, but is vastly preferable
 * to unrecoverable session crashes.
 *
 * Supports any Gemini model name pattern including custom user-defined models.
 * Detection checks model.id, model.providerID, and model.api.id/npm fields.
 */

const SENTINEL = "skip_thought_signature_validator"

/**
 * Check if a Model object (from chat.params input) is a Gemini model.
 * Checks multiple fields to catch all configurations:
 *   - model.id contains "gemini"
 *   - model.api.id contains "gemini"
 *   - model.api.npm is "@ai-sdk/google" or "@ai-sdk/google-vertex"
 *   - model.providerID contains "google"
 */
function isGeminiModel(model: any): boolean {
  if (!model) return false
  const id = (model.id ?? "").toLowerCase()
  const apiId = (model.api?.id ?? "").toLowerCase()
  const npm = (model.api?.npm ?? "").toLowerCase()
  const provider = (model.providerID ?? "").toLowerCase()

  if (id.includes("gemini") || apiId.includes("gemini")) return true
  if (npm === "@ai-sdk/google" || npm === "@ai-sdk/google-vertex") return true
  // Catch google-native provider but not unrelated providers
  if (provider === "google" || provider === "google-vertex") return true

  return false
}

/**
 * Check if an AssistantMessage info was generated by a Gemini model.
 * AssistantMessage has providerID + modelID fields (different from Model type).
 */
function isGeminiMessage(info: any): boolean {
  if (!info || info.role !== "assistant") return false
  const modelID = (info.modelID ?? "").toLowerCase()
  const providerID = (info.providerID ?? "").toLowerCase()
  const combined = `${providerID}/${modelID}`

  if (combined.includes("gemini")) return true
  if (providerID === "google" || providerID === "google-vertex") return true

  return false
}

/** Ensure metadata has a valid google.thoughtSignature, injecting sentinel if missing */
function ensureThoughtSignature(metadata: Record<string, any> | undefined): Record<string, any> {
  const meta = metadata ?? {}
  const google = (meta.google ?? {}) as Record<string, any>

  // Already has a real signature (base64 encoded, typically 100+ chars) — leave it alone
  if (google.thoughtSignature && typeof google.thoughtSignature === "string" && google.thoughtSignature.length > 40) {
    return meta
  }

  return {
    ...meta,
    google: {
      ...google,
      thoughtSignature: SENTINEL,
    },
  }
}

const plugin: Plugin = async (_ctx) => {
  // Track whether current session is using a Gemini model.
  // Set by chat.params which fires inside LLM.stream().
  //
  // Hook ordering: experimental.chat.messages.transform fires BEFORE chat.params
  // in each loop iteration (prompt.ts:648 vs llm.ts:114). This means on the very
  // first step, activeGemini is false. This is fine because step 1 has no historical
  // assistant messages to fix. From step 2 onwards (where historical messages with
  // potentially missing signatures exist), activeGemini will have been set by the
  // previous step's chat.params call.
  let activeGemini = false

  return {
    /**
     * chat.params fires before each LLM call (inside LLM.stream at llm.ts:114).
     * We use it to detect the current model for the messages transform hook.
     *
     * Model type fields: model.id, model.providerID, model.api.id, model.api.npm
     */
    "chat.params": async (input, _output) => {
      activeGemini = isGeminiModel(input.model)
    },

    /**
     * experimental.chat.messages.transform fires before toModelMessages() at
     * prompt.ts:648. We walk all assistant messages and ensure every reasoning
     * and tool part has metadata containing a valid thoughtSignature.
     *
     * This runs BEFORE the `differentModel` check in toModelMessages()
     * (message-v2.ts:589), so the metadata we inject will be present when
     * toModelMessages builds the UIMessage parts with providerMetadata.
     */
    "experimental.chat.messages.transform": async (_input, output) => {
      if (!activeGemini) return

      for (const msg of output.messages) {
        if (!isGeminiMessage(msg.info)) continue

        for (const part of msg.parts) {
          if (part.type === "reasoning") {
            ;(part as any).metadata = ensureThoughtSignature((part as any).metadata)
          }
          if (part.type === "tool") {
            ;(part as any).metadata = ensureThoughtSignature((part as any).metadata)
          }
        }
      }
    },
  }
}

export default plugin
